### ISSUE TITLE
Remove margin from child elements

### ISSUE THREAD

**Issue by roelmagdaleno** [roelmagdaleno/callout-block#2]
Apply this CSS code, so all elements inside the box won't include margin:

```css
.wp-block-roelmagdaleno-callout-box > * {
    margin: 0;
}
```

We're gonna use `gap` property to separate the children elements (#1).
